version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      #- static-content:/usr/share/nginx/html
      - "./vue/my-project/dist/:/usr/share/nginx/html/"


#volumes:
#  static-content:
