version: "3"
services:
  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN=jbrjga.com
    ports:
      - "80:80"
    restart: "always"
    environment:
      - NODE_ENV=production
  simpleapp:
    build:
      context: ../server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    entrypoint:
      - npm
      - run
      - start:prod
